function result = add(obj,a,b)
%add(obj,a,b)
%
%   Service definition of function ns__add
%   
%     Input:
%       a = (double)
%       b = (double)
%   
%     Output:
%       result = (double)

% Build up the argument lists.
values = { ...
   a, ...
   b, ...
   };
names = { ...
   'a', ...
   'b', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'urn:IoSteerWS', ...
    'add', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
result = parseSoapResponse(response);
